apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    gcb-build-id: 7024446e-25cd-49de-a23b-f87be543d6b4
    gcb-trigger-id: e99f5560-7983-46a5-9f01-69ba9a5e7b7d
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"4","gcb-build-id":"7024446e-25cd-49de-a23b-f87be543d6b4","gcb-trigger-id":"e99f5560-7983-46a5-9f01-69ba9a5e7b7d"},"creationTimestamp":"2021-05-18T01:31:58Z","generation":4,"labels":{"app":"nginx-1","app.kubernetes.io/managed-by":"gcp-cloud-build-deploy","app.kubernetes.io/name":"exp-app","app.kubernetes.io/version":"9e08858fefd0140ff2ca29c4bbd5afdc6e25ddda"},"managedFields":[{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:labels":{".":{},"f:app":{}}},"f:spec":{"f:progressDeadlineSeconds":{},"f:replicas":{},"f:revisionHistoryLimit":{},"f:selector":{"f:matchLabels":{".":{},"f:app":{}}},"f:strategy":{"f:rollingUpdate":{".":{},"f:maxSurge":{},"f:maxUnavailable":{}},"f:type":{}},"f:template":{"f:metadata":{"f:labels":{".":{},"f:app":{}}},"f:spec":{"f:containers":{"k:{\"name\":\"github-krish-kp-express-app-sha256-1\"}":{".":{},"f:image":{},"f:imagePullPolicy":{},"f:name":{},"f:ports":{".":{},"k:{\"containerPort\":3000,\"protocol\":\"TCP\"}":{".":{},"f:containerPort":{},"f:protocol":{}}},"f:resources":{},"f:terminationMessagePath":{},"f:terminationMessagePolicy":{}}},"f:dnsPolicy":{},"f:restartPolicy":{},"f:schedulerName":{},"f:securityContext":{},"f:terminationGracePeriodSeconds":{}}}}},"manager":"GoogleCloudConsole","operation":"Update","time":"2021-05-18T01:39:21Z"},{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:deployment.kubernetes.io/revision":{}}},"f:status":{"f:availableReplicas":{},"f:conditions":{".":{},"k:{\"type\":\"Available\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}},"k:{\"type\":\"Progressing\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}}},"f:observedGeneration":{},"f:readyReplicas":{},"f:replicas":{},"f:updatedReplicas":{}}},"manager":"kube-controller-manager","operation":"Update","time":"2021-05-18T01:39:26Z"}],"name":"nginx-1","namespace":"default","resourceVersion":"20628","selfLink":"/apis/apps/v1/namespaces/default/deployments/nginx-1","uid":"2702f658-d3fc-41e3-8582-410b7040463c"},"spec":{"progressDeadlineSeconds":600,"replicas":3,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"nginx-1"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"gcb-build-id":"7024446e-25cd-49de-a23b-f87be543d6b4","gcb-trigger-id":"e99f5560-7983-46a5-9f01-69ba9a5e7b7d"},"creationTimestamp":null,"labels":{"app":"nginx-1","app.kubernetes.io/managed-by":"gcp-cloud-build-deploy","app.kubernetes.io/name":"exp-app","app.kubernetes.io/version":"9e08858fefd0140ff2ca29c4bbd5afdc6e25ddda"}},"spec":{"containers":[{"image":"gcr.io/mindful-linker-313918/github_krish-kp_express-app@sha256:5306a709a30885fefd7b050484e8d90bf12e990f70e371b75dfc75aaa1159576","imagePullPolicy":"IfNotPresent","name":"github-krish-kp-express-app-sha256-1","ports":[{"containerPort":3000,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":3,"conditions":[{"lastTransitionTime":"2021-05-18T01:32:00Z","lastUpdateTime":"2021-05-18T01:32:00Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2021-05-18T01:31:58Z","lastUpdateTime":"2021-05-18T01:39:26Z","message":"ReplicaSet \"nginx-1-798949d888\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":4,"readyReplicas":3,"replicas":3,"updatedReplicas":3}}
  creationTimestamp: "2021-05-18T01:31:58Z"
  generation: 5
  labels:
    app: nginx-1
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
    app.kubernetes.io/name: exp-app
    app.kubernetes.io/version: 9e08858fefd0140ff2ca29c4bbd5afdc6e25ddda
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector:
          f:matchLabels:
            .: {}
            f:app: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:app: {}
          f:spec:
            f:containers:
              k:{"name":"github-krish-kp-express-app-sha256-1"}:
                .: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":3000,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:protocol: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
    manager: GoogleCloudConsole
    operation: Update
    time: "2021-05-18T01:39:21Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:gcb-build-id: {}
          f:gcb-trigger-id: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
      f:spec:
        f:template:
          f:metadata:
            f:annotations:
              .: {}
              f:gcb-build-id: {}
              f:gcb-trigger-id: {}
            f:labels:
              f:app.kubernetes.io/managed-by: {}
              f:app.kubernetes.io/name: {}
              f:app.kubernetes.io/version: {}
          f:spec:
            f:containers:
              k:{"name":"github-krish-kp-express-app-sha256-1"}:
                f:image: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-05-18T01:41:56Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-05-18T01:42:06Z"
  name: nginx-1
  namespace: default
  resourceVersion: "21646"
  selfLink: /apis/apps/v1/namespaces/default/deployments/nginx-1
  uid: 2702f658-d3fc-41e3-8582-410b7040463c
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        gcb-build-id: 7024446e-25cd-49de-a23b-f87be543d6b4
        gcb-trigger-id: e99f5560-7983-46a5-9f01-69ba9a5e7b7d
      creationTimestamp: null
      labels:
        app: nginx-1
        app.kubernetes.io/managed-by: gcp-cloud-build-deploy
        app.kubernetes.io/name: exp-app
        app.kubernetes.io/version: 9e08858fefd0140ff2ca29c4bbd5afdc6e25ddda
    spec:
      containers:
      - image: gcr.io/mindful-linker-313918/github_krish-kp_express-app@sha256:5306a709a30885fefd7b050484e8d90bf12e990f70e371b75dfc75aaa1159576
        imagePullPolicy: IfNotPresent
        name: github-krish-kp-express-app-sha256-1
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2021-05-18T01:32:00Z"
    lastUpdateTime: "2021-05-18T01:32:00Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-05-18T01:31:58Z"
    lastUpdateTime: "2021-05-18T01:42:06Z"
    message: ReplicaSet "nginx-1-68bc4d8f64" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 5
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
